BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Categories" (
	"categoryID"	INTEGER NOT NULL UNIQUE,
	"name"	INTEGER NOT NULL UNIQUE,
	PRIMARY KEY("categoryID")
);
CREATE TABLE IF NOT EXISTS "GroceryItems" (
	"itemID"	INTEGER NOT NULL UNIQUE,
	"name"	TEXT NOT NULL,
	"category"	INTEGER NOT NULL,
	PRIMARY KEY("itemID")
);
CREATE TABLE IF NOT EXISTS "GroceryList" (
	"entryID"	INTEGER NOT NULL UNIQUE,
	"itemID"	INTEGER NOT NULL,
	"quantity"	INTEGER NOT NULL DEFAULT 1,
	"priority"	INTEGER NOT NULL,
	"isChecked"	INTEGER NOT NULL DEFAULT 0 CHECK("isChecked" IN (0, 1)),
	PRIMARY KEY("entryID"),
	FOREIGN KEY("itemID") REFERENCES "GroceryItems"("itemID")
);
CREATE TABLE IF NOT EXISTS "Priorities" (
	"priorityID"	INTEGER NOT NULL,
	"name"	TEXT NOT NULL UNIQUE,
	PRIMARY KEY("priorityID")
);
INSERT INTO "Categories" ("categoryID","name") VALUES (1,'Dairy'),
 (2,'Beverages'),
 (3,'Deli'),
 (4,'Canned/Dried Foods'),
 (5,'Produce'),
 (6,'Baked Goods'),
 (7,'Frozen Foods'),
 (8,'Snacks'),
 (9,'Other');
INSERT INTO "GroceryItems" ("itemID","name","category") VALUES (1,'Milk',1),
 (2,'Block Cheese',1),
 (3,'Cream Cheese',1),
 (4,'Cottage Cheese',1),
 (5,'Cola',2),
 (6,'Diet Cola',2),
 (7,'Bottled Water',2),
 (8,'Orange Juice',2),
 (9,'Lemon-Lime Soda',2),
 (10,'Diet Lemon-Lime Soda',2),
 (11,'Iced Tea',2),
 (12,'Tea',2),
 (13,'Coffee',2),
 (14,'Frozen Vegetable',7),
 (15,'Frozen Fruit',7),
 (16,'Frozen Pizza',7),
 (17,'Ice Cream',7),
 (18,'Frozen French Fries',7),
 (19,'Frozen Chicken',7),
 (20,'Sliced Ham',3),
 (21,'Sliced Turkey',3),
 (22,'Sliced Roast Beef',3),
 (23,'Sliced Cheese',3),
 (24,'Canned Meat',4),
 (25,'Canned Fruit',4),
 (26,'Canned Vegetables',4),
 (27,'Canned Fish',4),
 (28,'Cereal',4),
 (29,'Dried Noodles',4),
 (30,'Apple',5),
 (31,'Banana',5),
 (32,'Orange',5),
 (33,'Lettuce',5),
 (34,'Broccoli',5),
 (35,'Carrot',5),
 (36,'White Bread Loaf',6),
 (37,'Sourdough Bread Loaf',6),
 (38,'Whole Wheat Bread Loaf',6),
 (39,'Cherry Pie',6),
 (40,'Apple Pie',6),
 (41,'Berry Pie',6),
 (42,'Muffins',6),
 (43,'Cake',6),
 (44,'Potato Chips',8),
 (45,'Tortilla Chips',8),
 (46,'Tortillas',6),
 (47,'Popcorn',8),
 (48,'Fruit Snacks',8),
 (49,'Trail Mix',8),
 (50,'Mixed Nuts',8),
 (51,'Hard Candy',8),
 (52,'Sour Candy',8),
 (53,'Gummy Candy',8),
 (54,'Bouillon Powder',9),
 (55,'Beef Broth',9),
 (56,'Bone Broth',9),
 (57,'Chicken Broth',9),
 (58,'Mushrooms',5);
INSERT INTO "Priorities" ("priorityID","name") VALUES (1,'Low'),
 (2,'Medium'),
 (3,'High');
COMMIT;
